// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Marreq

use printpdf::{
    BuiltinFont, Mm, Op, PdfDocument, PdfFontHandle, PdfPage, PdfSaveOptions, PdfWarnMsg, Point,
    Pt, TextItem,
};
// PDF helper functions and types
const PAGE_WIDTH: f32 = 210.0;
const PAGE_HEIGHT: f32 = 297.0;
const INITIAL_Y: f32 = 280.0;
const CONTENT_START_Y: f32 = 250.0;
const PAGE_BREAK_Y: f32 = 50.0;

fn push_text(ops: &mut Vec<Op>, font: BuiltinFont, size: f32, x: Mm, y: Mm, text: &str) {
    ops.push(Op::StartTextSection);
    ops.push(Op::SetTextCursor {
        pos: Point::new(x, y),
    });
    ops.push(Op::SetFont {
        font: PdfFontHandle::Builtin(font),
        size: Pt(size),
    });
    ops.push(Op::ShowText {
        items: vec![TextItem::Text(text.to_string())],
    });
    ops.push(Op::EndTextSection);
}

fn add_footer(ops: &mut Vec<Op>) {
    push_text(
        ops,
        BuiltinFont::Helvetica,
        8.0,
        Mm(20.0),
        Mm(20.0),
        "Generated by Marreq - Requirements Management System",
    );
}

fn add_page_number(ops: &mut Vec<Op>, page_number: usize) {
    push_text(
        ops,
        BuiltinFont::Helvetica,
        12.0,
        Mm(20.0),
        Mm(20.0),
        &format!("Page {}", page_number),
    );
}

fn save_pdf(
    mut doc: PdfDocument,
    pages_ops: Vec<Vec<Op>>,
) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    let pages = pages_ops
        .into_iter()
        .map(|ops| PdfPage::new(Mm(PAGE_WIDTH), Mm(PAGE_HEIGHT), ops))
        .collect();

    let mut warnings = Vec::<PdfWarnMsg>::new();
    let bytes = doc
        .with_pages(pages)
        .save(&PdfSaveOptions::default(), &mut warnings);
    Ok(bytes)
}

fn ensure_page_space(
    pages: &mut Vec<Vec<Op>>,
    current_page: &mut usize,
    y: &mut Mm,
    page_num: &mut usize,
) -> bool {
    if *y < Mm(PAGE_BREAK_Y) {
        *page_num += 1;
        pages.push(Vec::new());
        *current_page = pages.len() - 1;
        add_page_number(&mut pages[*current_page], *page_num);
        *y = Mm(INITIAL_Y);
        return true;
    }
    false
}

/// One row for the requirements PDF table: (id, title, reference, status, custom_values in definition order).
pub type RequirementsPdfRow = (i32, String, String, String, Vec<String>);

/// Generate a PDF document with a table of requirements (fixed columns + one per custom field).
pub fn generate_requirements_pdf_report(
    project_name: &str,
    rows: &[RequirementsPdfRow],
    custom_headers: &[String],
) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    let doc = PdfDocument::new("Marreq Requirements");
    let mut pages = vec![Vec::new()];
    let mut current_page = 0usize;
    let mut page_number = 1usize;

    push_text(
        &mut pages[current_page],
        BuiltinFont::HelveticaBold,
        16.0,
        Mm(20.0),
        Mm(INITIAL_Y),
        &format!("Requirements - {}", project_name),
    );
    let current_date = chrono::Utc::now().format("%Y-%m-%d %H:%M UTC");
    push_text(
        &mut pages[current_page],
        BuiltinFont::Helvetica,
        9.0,
        Mm(20.0),
        Mm(270.0),
        &format!("Generated on: {}", current_date),
    );

    let mut y = Mm(CONTENT_START_Y - 10.0);
    let header_cells: Vec<String> = ["ID", "Title", "Reference", "Status"]
        .into_iter()
        .map(String::from)
        .chain(custom_headers.iter().cloned())
        .collect();
    push_text(
        &mut pages[current_page],
        BuiltinFont::HelveticaBold,
        8.0,
        Mm(20.0),
        y,
        &header_cells.join(" | "),
    );
    y -= Mm(8.0);

    fn truncate(s: &str, max_chars: usize) -> String {
        let s = s.trim();
        if s.chars().count() <= max_chars {
            s.to_string()
        } else {
            format!("{}…", s.chars().take(max_chars - 1).collect::<String>())
        }
    }

    for (id, title, reference, status, custom_vals) in rows {
        if ensure_page_space(&mut pages, &mut current_page, &mut y, &mut page_number) {
            push_text(
                &mut pages[current_page],
                BuiltinFont::HelveticaBold,
                9.0,
                Mm(20.0),
                y,
                "Requirements (continued)",
            );
            y -= Mm(8.0);
        }
        let mut cells = vec![
            id.to_string(),
            truncate(title, 35),
            truncate(reference, 18),
            truncate(status, 12),
        ];
        cells.extend(custom_vals.iter().map(|v| truncate(v, 15)));
        push_text(
            &mut pages[current_page],
            BuiltinFont::Helvetica,
            7.0,
            Mm(20.0),
            y,
            &cells.join(" | "),
        );
        y -= Mm(6.0);
    }

    add_footer(&mut pages[0]);
    save_pdf(doc, pages)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Read;

    /// Concatenated content streams (Flate-compressed by printpdf) as text.
    fn pdf_page_text(pdf: &[u8]) -> String {
        let mut text = String::new();
        let mut rest = pdf;
        while let Some(start) = rest.windows(7).position(|w| w == b"stream\n") {
            let body = &rest[start + 7..];
            let Some(end) = body.windows(9).position(|w| w == b"endstream") else {
                break;
            };
            let mut decoded = String::new();
            if flate2::read::ZlibDecoder::new(&body[..end])
                .read_to_string(&mut decoded)
                .is_ok()
            {
                text.push_str(&decoded);
            }
            rest = &body[end..];
        }
        text
    }

    #[test]
    fn requirements_pdf_lists_each_row_with_custom_fields() {
        let rows: Vec<RequirementsPdfRow> = vec![(
            7,
            "Battery capacity".into(),
            "SAT-PWR-003".into(),
            "Draft".into(),
            vec!["Alice".into()],
        )];
        let pdf = generate_requirements_pdf_report("Satellite Demo", &rows, &["Owner".into()])
            .expect("pdf");
        assert!(pdf.starts_with(b"%PDF-"));
        let text = pdf_page_text(&pdf);
        for expected in [
            "Requirements - Satellite Demo",
            "Owner",
            "Battery capacity",
            "SAT-PWR-003",
        ] {
            assert!(text.contains(expected), "{expected} missing");
        }
    }
}
