version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'rust'
      POSTGRES_PASSWORD: 'rust'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
#   my-db: 
#    driver: local
  pgdata:

# networks:
#     default:
#         external:
#             name: somename_default

