[default.databases.my_db]
url = "postgres://rust:rust@db:5432/reqman"
pool_size = 10

[default]
port = 8000
address = "0.0.0.0"

[release]
secret_key = "8XuiJDYi9m8KbwspBnjctshHtRnhMxTqc6QQGJ7asJE="

