@startuml ER diagram

hide circle
skinparam linetype ortho

entity "Projects" as proj {
* project_id
---
* project_name
project_description
project_creation_date
project_update_date
project_status
project_owner_id
}

entity "Requirement" as req {
* id
---
* title
* description
* verification_method_id
* current_status_id
* author_id
* reviewer_id
* req_link
* reference_code
* category_id
* parent_id
* creation_date
* update_date
* deadline_date
* applicability_id
justification
* project_id
}

entity "Users" as user {
* user_id
---
* user_username
* user_name
* user_email
* user_creation_date
* user_last_login
* user_password
is_admin
}

entity "Status" as st {
* st_id
---
* st_title
* st_description
* st_short_name
}

entity "Categories" as cat {
* cat_id
---
* cat_title
* cat_description
* cat_tag
* project_id
}

entity "Applicability" as app {
* app_id
---
* app_title
* app_description
* app_tag
* project_id
}

entity "Tests" as test {
* test_id
---
* test_name
* test_description
* test_source
* test_status
* test_parent
* project_id
}

entity "Matrix" as matrix {
* matrix_req_id
* matrix_test_id
---
* matrix_creation_date
* project_id
}

entity "Verification" as verification {
* verification_id
---
* verification_name
* verification_description
}

proj ||--o{ req
proj ||--o{ user
proj ||--o{ cat
proj ||--o{ app
proj ||--o{ test
proj ||--o{ matrix

req  }|--|| st
req  }|--|| cat
req  }|--|| user
req  }|--|| verification
req  }|--|| app
test   }|--|| st
matrix ||--|| req
matrix ||--|| test

@enduml
