@startuml ER diagram

hide circle
skinparam linetype ortho

entity "Projects" as proj {
* project_id
---
* name
description
creation_date
update_date
status_id
owner_id
}

entity "Requirement" as req {
* id
---
* title
* description
* verification_method_id
* status_id
* author_id
* reviewer_id
* req_link
* reference_code
* category_id
* parent_id
* creation_date
* update_date
* deadline_date
* applicability_id
justification
* project_id
}

entity "Users" as user {
* id
---
* username
* name
* email
* creation_date
* last_login
* password_hash
is_admin
}

entity "Status" as st {
* id
---
* title
* description
* short_name
}

entity "Categories" as cat {
* id
---
* title
* description
* tag
* project_id
}

entity "Applicability" as app {
* id
---
* title
* description
* tag
* project_id
}

entity "Tests" as test {
* id
---
* name
* description
* source
* status_id
* parent_id
* project_id
}

entity "Matrix" as matrix {
* req_id
* id
---
* creation_date
* project_id
}

entity "Verification" as verification {
* id
---
* name
* description
}

proj ||--o{ req
proj ||--o{ user
proj ||--o{ cat
proj ||--o{ app
proj ||--o{ test
proj ||--o{ matrix

req  }|--|| st
req  }|--|| cat
req  }|--|| user
req  }|--|| verification
req  }|--|| app
test   }|--|| st
matrix ||--|| req
matrix ||--|| test

@enduml
