// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Marreq

//! Report documents with configurable sections (issue #354): a template
//! ([`definition::ReportDefinition`]) chooses the sections, their order and
//! options; [`sections`] turns project data into a format-neutral
//! [`model::Document`]; [`pdf`] (Typst) and [`odt`] write it out.

pub mod data;
pub mod definition;
pub mod model;
pub mod odt;
pub mod pdf;
pub mod sections;

use serde::{Deserialize, Serialize};

use crate::app::{AppState, DieselCachedRepo};
use crate::repository::errors::RepoError;
use definition::{PageSize, ReportDefinition};
use model::{DocMeta, Document};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReportFormat {
    Pdf,
    Odt,
}

impl ReportFormat {
    pub fn parse(ext: &str) -> Option<Self> {
        match ext {
            "pdf" => Some(ReportFormat::Pdf),
            "odt" => Some(ReportFormat::Odt),
            _ => None,
        }
    }

    pub fn extension(self) -> &'static str {
        match self {
            ReportFormat::Pdf => "pdf",
            ReportFormat::Odt => "odt",
        }
    }

    pub fn content_type(self) -> &'static str {
        match self {
            ReportFormat::Pdf => "application/pdf",
            ReportFormat::Odt => odt::MIME,
        }
    }
}

#[derive(Debug)]
pub enum ReportError {
    Repo(RepoError),
    /// The definition is invalid (400).
    Invalid(String),
    /// Layout or export failed (500).
    Render(String),
}

impl From<RepoError> for ReportError {
    fn from(e: RepoError) -> Self {
        ReportError::Repo(e)
    }
}

pub struct GeneratedReport {
    pub bytes: Vec<u8>,
    pub content_type: &'static str,
    pub filename: String,
}

/// Today's date, `YYYY-MM-DD` (UTC).
pub fn today() -> String {
    chrono::Utc::now()
        .date_naive()
        .format("%Y-%m-%d")
        .to_string()
}

/// Build the document model: validated definition + project data.
pub fn build_document(data: &data::ReportData, def: &ReportDefinition, date: &str) -> Document {
    let d = &def.document;
    let title = if d.title.trim().is_empty() {
        def.report_type.title().to_string()
    } else {
        d.title.trim().to_string()
    };
    let issue_label = match (d.issue.trim(), d.revision.trim()) {
        ("", "") => String::new(),
        (i, "") => format!("Issue {i}"),
        ("", r) => format!("Rev {r}"),
        (i, r) => format!("Issue {i} · Rev {r}"),
    };
    Document {
        meta: DocMeta {
            title,
            subtitle: def.report_type.description().into(),
            project: data.project_name.clone(),
            doc_id: d.doc_id.trim().to_string(),
            issue_label,
            classification: d.classification.trim().to_string(),
            date: date.to_string(),
            generated_by: format!(
                "Generated by Marreq {} on {date}",
                crate::build_info::backend_version()
            ),
            watermark: d
                .watermark
                .as_ref()
                .map(|w| w.trim().to_string())
                .filter(|w| !w.is_empty()),
            paper: match d.page_size {
                PageSize::A4 => "a4".into(),
                PageSize::Letter => "us-letter".into(),
            },
        },
        blocks: sections::render(data, def, date),
    }
}

/// File name: `{doc id or project slug}-{type}-{date}.{ext}`, safe characters only.
pub fn filename(def: &ReportDefinition, slug: &str, date: &str, format: ReportFormat) -> String {
    let base = if def.document.doc_id.trim().is_empty() {
        format!("{slug}-{}", def.report_type.key())
    } else {
        def.document.doc_id.trim().to_string()
    };
    let safe: String = base
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.') {
                c
            } else {
                '-'
            }
        })
        .collect();
    let safe = safe.trim_start_matches('.');
    format!("{safe}-{date}.{}", format.extension())
}

/// Validate the definition, load the project and render it. CPU-bound for
/// PDF: call it from `spawn_blocking`.
pub fn generate(
    state: &AppState<DieselCachedRepo>,
    project_id: i32,
    definition: ReportDefinition,
    format: ReportFormat,
) -> Result<GeneratedReport, ReportError> {
    let def = definition.validated().map_err(ReportError::Invalid)?;
    let data = data::load(state, project_id)?;
    let date = today();
    let doc = build_document(&data, &def, &date);
    let bytes = match format {
        ReportFormat::Pdf => pdf::render(&doc, def.document.pdf_a),
        ReportFormat::Odt => odt::render(&doc),
    }
    .map_err(ReportError::Render)?;
    Ok(GeneratedReport {
        bytes,
        content_type: format.content_type(),
        filename: filename(&def, &data.project_slug, &date, format),
    })
}

#[cfg(test)]
mod tests {
    use super::definition::{ReportType, SectionConfig};
    use super::sections::tests::{default_def, sample};
    use super::*;
    use std::io::Read;

    fn doc(t: ReportType) -> Document {
        build_document(&sample(), &default_def(t), "2026-10-03")
    }

    #[test]
    fn pdf_renders_every_report_type_with_landscape_matrix_pages() {
        for t in ReportType::ALL {
            let mut def = default_def(t);
            def.sections.iter_mut().for_each(|s| s.enabled = true);
            def.document.watermark = Some("DRAFT".into());
            let bytes = pdf::render(&build_document(&sample(), &def, "2026-10-03"), false)
                .unwrap_or_else(|e| panic!("{t:?}: {e}"));
            assert!(bytes.starts_with(b"%PDF-"), "{t:?}");
            assert!(bytes.len() > 20_000, "{t:?}: {} bytes", bytes.len());
        }
    }

    #[test]
    fn pdf_a_and_letter_paper_render() {
        let mut def = default_def(ReportType::Vcd);
        def.document.pdf_a = true;
        def.document.page_size = PageSize::Letter;
        let bytes = pdf::render(&build_document(&sample(), &def, "2026-10-03"), true).unwrap();
        let text = String::from_utf8_lossy(&bytes);
        assert!(
            text.contains("pdfaid"),
            "PDF/A identification in the XMP metadata"
        );
    }

    #[test]
    fn user_text_with_typst_syntax_is_printed_literally() {
        let mut data = sample();
        data.requirements[0].title =
            r#"#panic("x") $x$ *bold* _u_ <label> @ref [b] `c` \ // = - +"#.into();
        let mut def = default_def(ReportType::Vcd);
        def.document.title = r#"#set page(width: 1pt)"#.into();
        let bytes =
            pdf::render(&build_document(&data, &def, "2026-10-03"), false).expect("renders");
        assert!(bytes.starts_with(b"%PDF-"));
    }

    fn odt_parts(bytes: &[u8]) -> (Vec<String>, String, String, String) {
        let mut zip = zip::ZipArchive::new(std::io::Cursor::new(bytes)).unwrap();
        let names: Vec<String> = (0..zip.len())
            .map(|i| zip.by_index(i).unwrap().name().to_string())
            .collect();
        let first = zip.by_index(0).unwrap();
        assert_eq!(first.compression(), zip::CompressionMethod::Stored);
        drop(first);
        let mut read = |name: &str| {
            let mut s = String::new();
            zip.by_name(name).unwrap().read_to_string(&mut s).unwrap();
            s
        };
        (
            names,
            read("mimetype"),
            read("content.xml"),
            read("styles.xml"),
        )
    }

    fn well_formed(xml: &str) {
        let mut reader = quick_xml::Reader::from_str(xml);
        loop {
            match reader.read_event() {
                Ok(quick_xml::events::Event::Eof) => break,
                Ok(_) => {}
                Err(e) => panic!("malformed XML at {}: {e}", reader.buffer_position()),
            }
        }
    }

    #[test]
    fn odt_is_a_valid_package_with_headings_in_template_order() {
        let mut data = sample();
        data.requirements[0].title = "Power & <thermal> \"margins\"\u{1}".into();
        let mut def = default_def(ReportType::Vcd);
        def.sections.reverse();
        let bytes = odt::render(&build_document(&data, &def, "2026-10-03")).unwrap();
        let (names, mimetype, content, styles) = odt_parts(&bytes);
        assert_eq!(names[0], "mimetype");
        assert_eq!(mimetype, odt::MIME);
        for n in [
            "META-INF/manifest.xml",
            "meta.xml",
            "styles.xml",
            "content.xml",
            "Pictures/logo.png",
        ] {
            assert!(names.contains(&n.to_string()), "{n}");
        }
        well_formed(&content);
        well_formed(&styles);
        assert!(content.contains("Power &amp; &lt;thermal&gt; &quot;margins&quot;"));
        assert!(content.contains("table:table-header-rows"));
        assert!(content.contains("style:master-page-name=\"Landscape\""));
        assert!(styles.contains("<text:page-number"));
        assert!(
            content.contains("xlink:href=\"Pictures/logo.png\""),
            "cover logo"
        );
        assert!(styles.contains("draw:name=\"HeaderLogo1\""), "header logo");
        let pos = |s: &str| content.find(s).unwrap_or_else(|| panic!("{s} missing"));
        assert!(
            pos("Traceability checks") < pos("Verification control matrix"),
            "reversed template: checks come before the matrix"
        );
    }

    #[test]
    fn disabled_sections_are_absent_from_both_formats() {
        let mut def = default_def(ReportType::Coverage);
        def.sections = vec![SectionConfig {
            key: "suspect_links".into(),
            enabled: true,
            options: Default::default(),
        }];
        let def = def.validated().unwrap();
        let d = build_document(&sample(), &def, "2026-10-03");
        let (_, _, content, _) = odt_parts(&odt::render(&d).unwrap());
        assert!(content.contains("Suspect links"));
        assert!(!content.contains("Coverage summary"));
        assert!(!content.contains("Change record"));
        assert!(pdf::render(&d, false).is_ok());
    }

    #[test]
    fn filenames_are_safe() {
        let mut def = default_def(ReportType::Vcd);
        assert_eq!(
            filename(&def, "satellite-demo", "2026-10-03", ReportFormat::Pdf),
            "SATELLITE-DEMO-VCD-001-2026-10-03.pdf"
        );
        def.document.doc_id = "../a b/ç".into();
        assert_eq!(
            filename(&def, "x", "2026-10-03", ReportFormat::Odt),
            "-a-b---2026-10-03.odt"
        );
        def.document.doc_id = String::new();
        assert_eq!(
            filename(&def, "sat", "2026-10-03", ReportFormat::Odt),
            "sat-vcd-2026-10-03.odt"
        );
    }

    #[test]
    fn document_meta_uses_the_settings() {
        let d = doc(ReportType::Coverage);
        assert_eq!(d.meta.title, "Traceability & Coverage Report");
        assert_eq!(d.meta.issue_label, "Issue 1 · Rev 0");
        assert_eq!(d.meta.paper, "a4");
        assert!(d.meta.generated_by.contains("on 2026-10-03"));
    }
}
