// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Marreq

//! Format-neutral document model. Sections produce [`Block`]s; the PDF
//! (Typst) and ODT renderers lay them out. Section numbers are assigned here,
//! so both formats number headings identically.

use serde::Serialize;

/// A rendered report: document metadata plus its blocks in order.
#[derive(Debug, Clone, Serialize)]
pub struct Document {
    pub meta: DocMeta,
    pub blocks: Vec<Block>,
}

/// What the page frame needs (running header, footer, PDF metadata).
#[derive(Debug, Clone, Serialize)]
pub struct DocMeta {
    pub title: String,
    pub subtitle: String,
    pub project: String,
    pub doc_id: String,
    /// e.g. "Issue 1 · Rev 0".
    pub issue_label: String,
    pub classification: String,
    /// `YYYY-MM-DD`.
    pub date: String,
    /// e.g. "Generated by Marreq 0.1.11 on 2026-10-03".
    pub generated_by: String,
    pub watermark: Option<String>,
    /// `a4` or `us-letter`.
    pub paper: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Tone {
    Ok,
    Warn,
    Bad,
    Open,
    None,
}

/// A run of text inside a paragraph or cell.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(tag = "t", rename_all = "snake_case")]
pub enum Inline {
    Text { text: String },
    Bold { text: String },
    Muted { text: String },
    Code { text: String },
    Badge { tone: Tone, text: String },
    LineBreak,
}

impl Inline {
    pub fn text(s: impl Into<String>) -> Self {
        Inline::Text { text: s.into() }
    }
    pub fn bold(s: impl Into<String>) -> Self {
        Inline::Bold { text: s.into() }
    }
    pub fn muted(s: impl Into<String>) -> Self {
        Inline::Muted { text: s.into() }
    }
    pub fn code(s: impl Into<String>) -> Self {
        Inline::Code { text: s.into() }
    }
    pub fn badge(tone: Tone, s: impl Into<String>) -> Self {
        Inline::Badge {
            tone,
            text: s.into(),
        }
    }

    /// Plain text of the run (ODT bookmarks, tests).
    pub fn plain(&self) -> &str {
        match self {
            Inline::Text { text }
            | Inline::Bold { text }
            | Inline::Muted { text }
            | Inline::Code { text }
            | Inline::Badge { text, .. } => text,
            Inline::LineBreak => "\n",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Align {
    Left,
    Center,
    Right,
}

#[derive(Debug, Clone, Serialize)]
pub struct Column {
    pub title: String,
    /// Relative width (fraction of the table width).
    pub width: f32,
    pub align: Align,
}

impl Column {
    pub fn new(title: impl Into<String>, width: f32) -> Self {
        Self {
            title: title.into(),
            width,
            align: Align::Left,
        }
    }
    pub fn right(mut self) -> Self {
        self.align = Align::Right;
        self
    }
    pub fn center(mut self) -> Self {
        self.align = Align::Center;
        self
    }
}

/// Part of a stacked bar.
#[derive(Debug, Clone, Serialize)]
pub struct BarPart {
    pub value: f64,
    pub tone: Tone,
}

#[derive(Debug, Clone, Serialize)]
#[serde(tag = "t", rename_all = "snake_case")]
pub enum Cell {
    Content { inlines: Vec<Inline> },
    Bar { parts: Vec<BarPart> },
}

impl Cell {
    pub fn text(s: impl Into<String>) -> Self {
        Cell::Content {
            inlines: vec![Inline::text(s)],
        }
    }
    pub fn of(inlines: Vec<Inline>) -> Self {
        Cell::Content { inlines }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum RowKind {
    Normal,
    /// A full-width group label (spans every column).
    Group,
    Total,
}

#[derive(Debug, Clone, Serialize)]
pub struct Row {
    pub kind: RowKind,
    pub cells: Vec<Cell>,
}

#[derive(Debug, Clone, Serialize)]
pub struct Table {
    pub columns: Vec<Column>,
    pub rows: Vec<Row>,
    /// Smaller type, for dense matrices.
    pub compact: bool,
}

impl Table {
    pub fn new(columns: Vec<Column>) -> Self {
        Self {
            columns,
            rows: Vec::new(),
            compact: false,
        }
    }
    pub fn row(&mut self, cells: Vec<Cell>) {
        self.rows.push(Row {
            kind: RowKind::Normal,
            cells,
        });
    }
    pub fn group(&mut self, label: impl Into<String>) {
        self.rows.push(Row {
            kind: RowKind::Group,
            cells: vec![Cell::text(label)],
        });
    }
    pub fn total(&mut self, cells: Vec<Cell>) {
        self.rows.push(Row {
            kind: RowKind::Total,
            cells,
        });
    }
}

#[derive(Debug, Clone, Serialize)]
pub struct Kpi {
    pub value: String,
    pub label: String,
    pub tone: Tone,
}

#[derive(Debug, Clone, Serialize)]
pub struct KeyValue {
    pub key: String,
    pub value: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct Signatory {
    pub role: String,
    pub name: String,
}

#[derive(Debug, Clone, Serialize)]
#[serde(tag = "t", rename_all = "snake_case")]
pub enum Block {
    Cover {
        kicker: String,
        title: String,
        subtitle: String,
        fields: Vec<KeyValue>,
        signatories: Vec<Signatory>,
        note: Option<String>,
    },
    Toc {
        title: String,
    },
    Heading {
        level: u8,
        /// "3" or "3.2"; empty for unnumbered headings.
        number: String,
        text: String,
        /// Listed in the table of contents.
        outlined: bool,
    },
    Paragraph {
        inlines: Vec<Inline>,
    },
    Bullets {
        items: Vec<Vec<Inline>>,
    },
    Table(Table),
    Kpis {
        items: Vec<Kpi>,
    },
    Legend {
        items: Vec<(Tone, String)>,
    },
    PageBreak,
    /// Blocks laid out on landscape pages.
    Landscape {
        blocks: Vec<Block>,
    },
}

impl Block {
    pub fn para(inlines: Vec<Inline>) -> Self {
        Block::Paragraph { inlines }
    }
    pub fn text(s: impl Into<String>) -> Self {
        Block::Paragraph {
            inlines: vec![Inline::text(s)],
        }
    }
}

/// Assigns "1", "1.1", … to numbered headings in document order (including
/// headings inside landscape blocks). Headings with `numbered = false` keep an
/// empty number.
pub struct Numbering {
    counters: [u32; 3],
}

impl Default for Numbering {
    fn default() -> Self {
        Self::new()
    }
}

impl Numbering {
    pub fn new() -> Self {
        Self { counters: [0; 3] }
    }

    pub fn next(&mut self, level: u8) -> String {
        let i = (level.clamp(1, 3) - 1) as usize;
        self.counters[i] += 1;
        for c in self.counters.iter_mut().skip(i + 1) {
            *c = 0;
        }
        self.counters[..=i]
            .iter()
            .map(u32::to_string)
            .collect::<Vec<_>>()
            .join(".")
    }
}

/// All headings in reading order, as `(number, text)` (tests, ODT contents).
pub fn headings(blocks: &[Block]) -> Vec<(u8, String, String, bool)> {
    let mut out = Vec::new();
    for b in blocks {
        match b {
            Block::Heading {
                level,
                number,
                text,
                outlined,
            } => out.push((*level, number.clone(), text.clone(), *outlined)),
            Block::Landscape { blocks } => out.extend(headings(blocks)),
            _ => {}
        }
    }
    out
}
